apiVersion: v1
kind: Service
metadata:
  name: cipherlink-backend
  namespace: cipherlink
  labels:
    app: cipherlink-backend
spec:
  selector:
    app: cipherlink-backend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
